source("R/load_data.R")

summary(daily_losses_window_a)
summary(daily_losses_window_b)
summary(mer_insurance_window_b)
summary(material_prices_window_a)
summary(material_prices_window_b)
summary(sde_blueprints_window_a)
summary(sde_blueprints_window_b)
summary(sde_types_window_a)
summary(sde_types_window_b)
summary(wars_window_a_active_by_week)
summary(wars_window_a_summary)
summary(wars_window_b_active_by_week)
summary(wars_window_b_summary)

mer_insurance_window_b %>% filter(insurance_net_isk < 0) %>% arrange(date) %>% print()
