daily_losses_window_a <- read.csv("data/aggregated/daily_losses_window_a.csv")
daily_losses_window_b <- read.csv("data/aggregated/daily_losses_window_b.csv")
mer_insurance_window_b <- read.csv("data/aggregated/mer_insurance_window_b.csv")
material_prices_window_a <- read.csv("data/aggregated/material_prices_window_a.csv")
material_prices_window_b <- read.csv("data/aggregated/material_prices_window_b.csv.gz")
sde_blueprints_window_a <- read.csv("data/aggregated/sde_blueprints_window_a.csv")
sde_blueprints_window_b <- read.csv("data/aggregated/sde_blueprints_window_b.csv")
sde_types_window_a <- read.csv("data/aggregated/sde_types_window_a.csv")
sde_types_window_b <- read.csv("data/aggregated/sde_types_window_b.csv")
wars_window_a_active_by_week <- read.csv("data/aggregated/wars_window_a_active_by_week.csv")
wars_window_a_summary <- read.csv("data/aggregated/wars_window_a_summary.csv")
wars_window_b_active_by_week <- read.csv("data/aggregated/wars_window_b_active_by_week.csv")
wars_window_b_summary <- read.csv("data/aggregated/wars_window_b_summary.csv")

summary(daily_losses_window_a)
summary(daily_losses_window_b)
summary(mer_insurance_window_b)
summary(material_prices_window_a)
summary(material_prices_window_b)
summary(sde_blueprints_window_a)
summary(sde_blueprints_window_b)
summary(sde_types_window_a)
summary(sde_types_window_b)
summary(wars_window_a_active_by_week)
summary(wars_window_a_summary)
summary(wars_window_b_active_by_week)
summary(wars_window_b_summary)

daily_losses_window_a$date <- as.Date(daily_losses_window_a$date)
daily_losses_window_b$date <- as.Date(daily_losses_window_b$date)
material_prices_window_a$date <- as.Date(material_prices_window_a$date)
material_prices_window_b$date <- as.Date(material_prices_window_b$date)
sde_blueprints_window_a$snapshot <- as.Date(sde_blueprints_window_a$snapshot)
sde_blueprints_window_b$snapshot <- as.Date(sde_blueprints_window_b$snapshot, format="%Y%m%d")
mer_insurance_window_b$date <- as.Date(mer_insurance_window_b$date)
