library(data.table)
library(dplyr)

daily_losses_window_a <- fread("data/aggregated/daily_losses_window_a.csv")
daily_losses_window_b <- fread("data/aggregated/daily_losses_window_b.csv")
mer_insurance_window_b <- fread("data/aggregated/mer_insurance_window_b.csv")
material_prices_window_a <- fread("data/aggregated/material_prices_window_a.csv")
material_prices_window_b <- fread("data/aggregated/material_prices_window_b.csv.gz")
sde_blueprints_window_a <- fread("data/aggregated/sde_blueprints_window_a.csv")
sde_blueprints_window_b <- fread("data/aggregated/sde_blueprints_window_b.csv")
sde_types_window_a <- fread("data/aggregated/sde_types_window_a.csv")
sde_types_window_b <- fread("data/aggregated/sde_types_window_b.csv")
wars_window_a_active_by_week <- fread("data/aggregated/wars_window_a_active_by_week.csv")
wars_window_a_summary <- fread("data/aggregated/wars_window_a_summary.csv")
wars_window_b_active_by_week <- fread("data/aggregated/wars_window_b_active_by_week.csv")
wars_window_b_summary <- fread("data/aggregated/wars_window_b_summary.csv")

daily_losses_window_a$date <- as.Date(daily_losses_window_a$date)
daily_losses_window_b$date <- as.Date(daily_losses_window_b$date)
material_prices_window_a$date <- as.Date(material_prices_window_a$date)
material_prices_window_b$date <- as.Date(material_prices_window_b$date)
sde_blueprints_window_a$snapshot <- as.Date(sde_blueprints_window_a$snapshot)
sde_blueprints_window_b$snapshot <- as.Date(sde_blueprints_window_b$snapshot, format="%Y%m%d")
mer_insurance_window_b$date <- as.Date(mer_insurance_window_b$date)

mineral_ids <- c(34, 35, 36, 37, 38, 39, 40, 11399)
